volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: lenevi/kittygram_backend:latest
    restart: always
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - postgres

  frontend:
    image: lenevi/kittygram_frontend:latest
    restart: always
    command: >
      sh -c "cp -r /app/build/static/. /static/ &&
             cp /app/build/index.html /app/build/asset-manifest.json /app/build/favicon.ico /app/build/manifest.json /app/build/robots.txt /static/"
    volumes:
      - static:/static

  gateway:
    image: lenevi/kittygram_gateway:latest
    restart: always
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend